{
  config,
  lib,
  pkgs,
  ...
}:

# ============================================================================
# Tier 1 of the Nagios <-> Prometheus reverse mirror
# (docs/NAGIOS_PROMETHEUS_MIRROR_SPEC.md, section 3).
#
# Independent *measurements* that re-validate Prometheus's highest-value
# coverage WITHOUT touching any Prometheus / Loki / VictoriaMetrics API.
# Three hand-curated families, each generated by `lib.concatMapStrings` over a
# data list:
#
#   1. Textfile-collector freshness  (~48 check_file_age services)
#   2. systemd unit gap              (units Prometheus watches but Nagios
#                                      did not check_systemd_service yet)
#   3. nginx vhost gap               (vhosts only blackbox-probed today)
#
# All services attach to host_name vulcan and servicegroup
# `prometheus-mirror-tier1`. This is a separate module from the tier-2 IFD
# generator so the hand-curated lists and the import-from-derivation machinery
# never mix (spec 3, file manifest).
# ============================================================================

let
  hostName = "vulcan";
  serviceGroup = "prometheus-mirror-tier1";

  textfileDir = "/var/lib/prometheus-node-exporter-textfiles";

  inherit (lib) concatMapStrings;

  # --------------------------------------------------------------------------
  # FAMILY 1 — textfile-collector freshness.
  #
  # check_file_age -w <warn> -c <crit> -f <textfileDir>/<file>; thresholds in
  # SECONDS. Rule (spec 3.1 + the operator's collector table):
  #   warn = 3x writer cadence, crit = 6x cadence, floor 10 min (600s);
  #   daily writers default to warn 26h / crit 50h;
  #   weekly CVE -> warn 8d / crit 15d;
  #   the two self-heal daemons (no fixed cadence) -> warn 2h / crit 6h.
  # `template` picks the Nagios check interval: "standard" (5 min) for
  # cadences <= 1h, "low" (15 min, low-priority-service) for daily / weekly /
  # daemon / 6h-event-driven entries.
  #
  # EXCLUDED (orphaned — writers removed Nov 2025, files deleted at deploy):
  #   paperless.prom, paperless_ai.prom  (writers removed Nov 2025)
  #   schwab_token.prom                  (writer deleted 2026-07-29 with plan item D3,
  #                                       which retired the Schwab source. Its check was left
  #                                       behind and became the ONLY critical on the host,
  #                                       pinning NagiosServicesCritical permanently on so
  #                                       that a real second critical produced no transition.
  #                                       A freshness check on a file that will never be
  #                                       written again is a permanent CRITICAL, not a monitor.
  # --------------------------------------------------------------------------
  textfileChecks = [
    # 1m cadence -> floored to 600s warn = 600s crit
    {
      file = "asymmetric_routing.prom";
      warn = 600;
      crit = 600;
      template = "standard";
    }
    {
      file = "atd.prom";
      warn = 600;
      crit = 600;
      template = "standard";
    }
    {
      file = "hermes_fallback.prom";
      warn = 600;
      crit = 600;
      template = "standard";
    }
    {
      file = "microvm_resources.prom";
      warn = 600;
      crit = 600;
      template = "standard";
    }
    {
      file = "nodered_safety.prom";
      warn = 600;
      crit = 600;
      template = "standard";
    }
    {
      file = "openclaw_canary.prom";
      warn = 600;
      crit = 600;
      template = "standard";
    }

    # 2m cadence -> 3x = 360 / 6x = 720
    {
      file = "container_health.prom";
      warn = 360;
      crit = 720;
      template = "standard";
    }
    {
      file = "nagios_status.prom";
      warn = 360;
      crit = 720;
      template = "standard";
    }
    {
      file = "zfs_pool_health.prom";
      warn = 360;
      crit = 720;
      template = "standard";
    }

    # 5m cadence -> 900 / 1800
    {
      file = "dns_correctness.prom";
      warn = 900;
      crit = 1800;
      template = "standard";
    }
    {
      file = "drafts_mcp.prom";
      warn = 900;
      crit = 1800;
      template = "standard";
    }
    {
      file = "hermes_e2e_chat.prom";
      warn = 900;
      crit = 1800;
      template = "standard";
    }
    {
      file = "hermes_health.prom";
      warn = 900;
      crit = 1800;
      template = "standard";
    }
    {
      file = "home_assistant_backup.prom";
      warn = 900;
      crit = 1800;
      template = "standard";
    }
    {
      file = "imapsieve.prom";
      warn = 900;
      crit = 1800;
      template = "standard";
    }
    {
      file = "openclaw_mcporter.prom";
      warn = 900;
      crit = 1800;
      template = "standard";
    }
    {
      file = "port_drift.prom";
      warn = 900;
      crit = 1800;
      template = "standard";
    }

    # 15m cadence -> 2700 / 5400
    {
      file = "backup_status.prom";
      warn = 2700;
      crit = 5400;
      template = "standard";
    }
    {
      # dual-writer (fast 15m + slow OnCalendar); use the fast cadence.
      file = "git_workspace.prom";
      warn = 2700;
      crit = 5400;
      template = "standard";
    }
    {
      file = "mbsync_bia.prom";
      warn = 2700;
      crit = 5400;
      template = "standard";
    }
    {
      file = "mbsync_johnw.prom";
      warn = 2700;
      crit = 5400;
      template = "standard";
    }
    {
      file = "openclaw_hermes_smoke.prom";
      warn = 2700;
      crit = 5400;
      template = "standard";
    }
    {
      file = "speedtest_results.prom";
      warn = 2700;
      crit = 5400;
      template = "standard";
    }

    # 1h cadence -> 10800 / 21600
    {
      file = "certificates.prom";
      warn = 10800;
      crit = 21600;
      template = "standard";
    }
    {
      file = "config_drift.prom";
      warn = 10800;
      crit = 21600;
      template = "standard";
    }
    {
      file = "microvm_state_share.prom";
      warn = 10800;
      crit = 21600;
      template = "standard";
    }
    {
      file = "secrets-perms.prom";
      warn = 10800;
      crit = 21600;
      template = "standard";
    }

    # 6h event-driven backup writers -> 64800 / 129600 (low-priority)
    {
      file = "flume_sync.prom";
      warn = 64800;
      crit = 129600;
      template = "low";
    }
    {
      file = "local-backup.prom";
      warn = 64800;
      crit = 129600;
      template = "low";
    }
    {
      file = "restic.prom";
      warn = 64800;
      crit = 129600;
      template = "low";
    }

    # daily cadence (default 26h / 50h) -> 93600 / 180000 (low-priority)
    {
      file = "aide.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }
    {
      file = "calendar_publisher.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }
    {
      file = "container_image_staleness.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }
    {
      file = "container_store_size.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }
    {
      file = "fts_staleness.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }
    {
      # templated mbsync; assembly instance is DAILY (timerInterval=1day).
      file = "mbsync_assembly.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }
    {
      file = "nodered_backup.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }
    {
      file = "openclaw_config_drift.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }
    {
      file = "system_age.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }
    # daily event-driven backup writers (explicit 26h / 50h)
    {
      file = "pg_dump.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }
    {
      file = "rclone-gdrive.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }
    {
      file = "rclone-onedrive.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }
    {
      file = "technitium_backup.prom";
      warn = 93600;
      crit = 180000;
      template = "low";
    }

    # weekly CVE scan -> warn 8d (691200) / crit 15d (1296000)
    {
      file = "container_cve.prom";
      warn = 691200;
      crit = 1296000;
      template = "low";
    }

    # self-heal daemons (no fixed cadence) -> generous warn 2h / crit 6h
    {
      file = "hermes_self_heal.prom";
      warn = 7200;
      crit = 21600;
      template = "low";
    }
    {
      file = "openclaw_self_heal.prom";
      warn = 7200;
      crit = 21600;
      template = "low";
    }
  ];

  templateName = t: if t == "low" then "low-priority-service" else "standard-service";

  # Strip the trailing ".prom" and tidy separators for the display name.
  fileToDesc =
    file:
    let
      base = lib.removeSuffix ".prom" file;
    in
    builtins.replaceStrings [ "_" "-" ] [ " " " " ] base;

  mkTextfileCheck = c: ''

    # ${c.file} (warn ${toString c.warn}s / crit ${toString c.crit}s)
    define service {
      use                     ${templateName c.template}
      host_name               ${hostName}
      service_description     PROM-T1 Textfile Fresh: ${fileToDesc c.file}
      check_command           check_file_age_tier1!${toString c.warn}!${toString c.crit}!${textfileDir}/${c.file}
      service_groups          ${serviceGroup}
    }
  '';

  # --------------------------------------------------------------------------
  # FAMILY 2 — systemd unit gap.
  #
  # Units Prometheus watches via node_systemd_unit_state that Nagios's existing
  # check_systemd_service set did NOT already cover (recon
  # .tier1.systemd_units_prometheus_watches minus
  # .tier1.systemd_units_nagios_already_checks, reconciled against the recon's
  # authoritative OVERLAP note). Reuses the GLOBAL check_systemd_service
  # command defined once in modules/services/nagios.nix
  # (check_systemd -u <unit> -w 600 -c 900); that plugin works for both
  # .service and .socket units (it does not hardcode a .service suffix), so
  # podman.socket is emitted with its explicit .socket unit name.
  #
  # SKIPPED (already covered, not re-added):
  #   qdrant.service     -> qdrant-nagios.nix satellite module
  #   sshd.service       -> a stronger functional `check_ssh` probe exists
  # SKIPPED (non-concrete regex / template / wildcard matchers, cannot map 1:1):
  #   (sshd|postgresql|nginx|prometheus|tailscaled|step-ca|docker).service,
  #   prometheus.*.service, restic-backups-.*.service, restic-backups-.*.timer,
  #   .*\.service, redis-(gitea|immich).service,
  #   budget-board-(server|client).service
  #   (the budget-board regex expands to the two concrete units below)
  # --------------------------------------------------------------------------
  systemdGapChecks = [
    {
      unit = "NetworkManager.service";
      desc = "NetworkManager";
    }
    {
      unit = "prometheus-blackbox-exporter.service";
      desc = "Blackbox Exporter";
    }
    {
      unit = "home-manager-vane.service";
      desc = "Home-Manager (vane)";
    }
    {
      # Nagios checks vdirsyncer-status.service + vdirsyncer.timer, NOT the
      # vdirsyncer.service unit itself.
      unit = "vdirsyncer.service";
      desc = "vdirsyncer Sync";
    }
    {
      unit = "budget-board-server.service";
      desc = "BudgetBoard Server";
    }
    {
      unit = "budget-board-client.service";
      desc = "BudgetBoard Client";
    }
    {
      unit = "budget-board-pod.service";
      desc = "BudgetBoard Pod";
    }
    {
      # Nagios checks the github-mirror.timer, not the .service.
      unit = "github-mirror.service";
      desc = "GitHub Mirror";
    }
    {
      # check_systemd handles .socket units (systemctl is-active style).
      unit = "podman.socket";
      desc = "Podman Socket";
    }
  ];

  mkSystemdCheck = c: ''

    define service {
      use                     standard-service
      host_name               ${hostName}
      service_description     PROM-T1 Unit: ${c.desc}
      check_command           check_systemd_service!${c.unit}
      service_groups          ${serviceGroup}
    }
  '';

  # --------------------------------------------------------------------------
  # FAMILY 3 — nginx vhost gap.
  #
  # The vhosts Prometheus blackbox-probes (modules/services/blackbox-monitoring
  # .nix: blackbox_https_local + blackbox_https_auth) that have NO independent
  # Nagios check_http/check_https service today (nagios.nix carries 14 such
  # checks as of 2026-07-27 — 12 check_http! + 2 check_https! — plus the
  # atd/qdrant satellite checks). memory.vulcan.lan is deliberately absent
  # from the list below even though it IS blackbox-probed locally (job
  # blackbox_memory_vault, blackbox-monitoring.nix): nagios.nix already has
  # its own Memory-Vault Health check_https for that vhost, so it is not a
  # gap. New local command
  # `check_https_vhost` mirrors the blackbox local probe:
  #   check_http -H <vhost> -S --sni -I 127.0.0.1 -w 5 -c 10
  # (the existing global check_https command sends -H $HOSTADDRESS$ and cannot
  # target a per-vhost SNI name through 127.0.0.1, so one new command is
  # defined here.) Verified live: an unauth vhost returns 2xx/3xx -> exit 0.
  #
  # The two auth-gated / no-root-handler vhosts (nagios, loki —
  # blackbox_https_auth) are probed by `check_https_vhost_auth`, whose `-e`
  # list mirrors the blackbox https_2xx_or_auth module's valid_status_codes
  # (200/301/302/303/307/308/401/403/404) exactly: the assertion is TLS +
  # nginx vhost reachability, not app-level routing. loki returns 404 from
  # localhost (the / location proxies straight to Loki, which has no root
  # handler) — accepting only 401/200/302 made the check born-CRITICAL
  # (2026-06-11). Verified live with the full list: nagios -> exit 0,
  # loki 404 -> exit 0.
  #
  # KEEP-IN-SYNC: this list duplicates the blackbox target arrays as plain
  # data. Tier 3 (the divergence reconciler) catches semantic drift.
  # --------------------------------------------------------------------------
  vhostGapChecks = [
    { vhost = "glance.vulcan.lan"; }
    { vhost = "cockpit.vulcan.lan"; }
    { vhost = "dns.vulcan.lan"; }
    { vhost = "postgres.vulcan.lan"; }
    { vhost = "hass.vulcan.lan"; }
    { vhost = "nodered.vulcan.lan"; }
    { vhost = "jellyfin.vulcan.lan"; }
    { vhost = "prometheus.vulcan.lan"; }
    { vhost = "victoriametrics.vulcan.lan"; }
    { vhost = "grafana.vulcan.lan"; }
    { vhost = "glances.vulcan.lan"; }
    { vhost = "alertmanager.vulcan.lan"; }
    { vhost = "aria.vulcan.lan"; }
    { vhost = "chat.vulcan.lan"; }
    { vhost = "searxng.vulcan.lan"; }
    { vhost = "speedtracker.vulcan.lan"; }
    { vhost = "gitea.vulcan.lan"; }
    { vhost = "immich.vulcan.lan"; }
    { vhost = "jupyter.vulcan.lan"; }
    { vhost = "kiwix.vulcan.lan"; }
    { vhost = "llama-swap.vulcan.lan"; }
    { vhost = "promtail.vulcan.lan"; }
    { vhost = "radicale.vulcan.lan"; }
    { vhost = "rspamd.vulcan.lan"; }
    { vhost = "vdirsyncer.vulcan.lan"; }
    { vhost = "zimit.vulcan.lan"; }
  ];

  # Auth-gated / no-root-handler vhosts (blackbox_https_auth): probed with the
  # full https_2xx_or_auth status list (2xx/3xx/401/403/404), not only 401 —
  # loki answers 404 from localhost (see the family header above).
  vhostAuthChecks = [
    { vhost = "nagios.vulcan.lan"; }
    { vhost = "loki.vulcan.lan"; }
  ];

  vhostToDesc = vhost: lib.removeSuffix ".vulcan.lan" vhost;

  mkVhostCheck = c: ''

    define service {
      use                     standard-service
      host_name               ${hostName}
      service_description     PROM-T1 HTTPS: ${vhostToDesc c.vhost}
      check_command           check_https_vhost!${c.vhost}
      service_groups          ${serviceGroup}
    }
  '';

  mkVhostAuthCheck = c: ''

    define service {
      use                     standard-service
      host_name               ${hostName}
      service_description     PROM-T1 HTTPS (auth): ${vhostToDesc c.vhost}
      check_command           check_https_vhost_auth!${c.vhost}
      service_groups          ${serviceGroup}
    }
  '';

  # --------------------------------------------------------------------------
  # Assemble the single object-definition blob.
  # --------------------------------------------------------------------------
  tier1ObjectDefs = pkgs.writeText "nagios-tier1-mirror.cfg" ''
    # ==========================================================================
    # Nagios Tier-1 Prometheus Mirror (generated)
    # docs/NAGIOS_PROMETHEUS_MIRROR_SPEC.md section 3.
    # Independent measurements: textfile freshness, systemd gap, vhost gap.
    # ==========================================================================

    # --- servicegroup --------------------------------------------------------
    define servicegroup {
      servicegroup_name  ${serviceGroup}
      alias              Independent mirrors of Prometheus coverage
    }

    # --- commands ------------------------------------------------------------
    # Textfile staleness (monitoring-plugins check_file_age):
    #   $ARG1$ = warn seconds, $ARG2$ = crit seconds, $ARG3$ = file path.
    define command {
      command_name    check_file_age_tier1
      command_line    ${pkgs.monitoring-plugins}/bin/check_file_age -w $ARG1$ -c $ARG2$ -f $ARG3$
    }

    # Per-vhost local HTTPS probe (SNI to 127.0.0.1), mirrors the blackbox
    # https_2xx_local module. $ARG1$ = vhost (SNI / Host header).
    define command {
      command_name    check_https_vhost
      command_line    ${pkgs.monitoring-plugins}/bin/check_http -H $ARG1$ -S --sni -I 127.0.0.1 -w 5 -c 10
    }

    # Auth-gated variant: a 401 challenge (or any status the blackbox
    # https_2xx_or_auth module accepts, incl. loki's no-root-handler 404)
    # counts as healthy — TLS + nginx are up.
    define command {
      command_name    check_https_vhost_auth
      command_line    ${pkgs.monitoring-plugins}/bin/check_http -H $ARG1$ -S --sni -I 127.0.0.1 -w 5 -c 10 -e 'HTTP/1.1 200,HTTP/2 200,HTTP/1.1 301,HTTP/2 301,HTTP/1.1 302,HTTP/2 302,HTTP/1.1 303,HTTP/2 303,HTTP/1.1 307,HTTP/2 307,HTTP/1.1 308,HTTP/2 308,HTTP/1.1 401,HTTP/2 401,HTTP/1.1 403,HTTP/2 403,HTTP/1.1 404,HTTP/2 404'
    }

    # --- Family 1: textfile-collector freshness (${toString (builtins.length textfileChecks)} checks) ---
    ${concatMapStrings mkTextfileCheck textfileChecks}

    # --- Family 2: systemd unit gap (${toString (builtins.length systemdGapChecks)} checks) ---
    ${concatMapStrings mkSystemdCheck systemdGapChecks}

    # --- Family 3: nginx vhost gap (${toString (builtins.length vhostGapChecks)} unauth + ${toString (builtins.length vhostAuthChecks)} auth) ---
    ${concatMapStrings mkVhostCheck vhostGapChecks}
    ${concatMapStrings mkVhostAuthCheck vhostAuthChecks}
  '';
in
{
  services.nagios.objectDefs = [ tier1ObjectDefs ];
}
