{ config, lib, pkgs, ... }:

let
  # Use sage package which includes jupyterlab with SageMath kernel pre-configured
  sage = pkgs.sage;
in
{
  # SOPS secrets for JupyterLab
  sops.secrets."jupyterlab/auth-token" = {
    owner = "root";  # DynamicUser will access via systemd LoadCredential
    mode = "0400";
    restartUnits = [ "jupyterlab.service" ];
  };

  # JupyterLab service configuration
  systemd.services.jupyterlab = {
    description = "JupyterLab Server with SageMath Kernel";
    after = [ "network-online.target" "sops-install-secrets.service" ];
    wants = [ "network-online.target" "sops-install-secrets.service" ];
    wantedBy = [ "multi-user.target" ];

    # Environment for JupyterLab
    environment = {
      # Set HOME for sage (needs to create .sage directory)
      HOME = "/var/lib/jupyter";

      # Set Jupyter config directory
      JUPYTER_CONFIG_DIR = "/var/lib/jupyter/config";
      JUPYTER_DATA_DIR = "/var/lib/jupyter/data";
      JUPYTER_RUNTIME_DIR = "/run/jupyter";

      # Use system CA bundle (includes step-ca root CA)
      SSL_CERT_FILE = "/etc/ssl/certs/ca-bundle.crt";
      REQUESTS_CA_BUNDLE = "/etc/ssl/certs/ca-bundle.crt";

      # Sage-specific environment
      DOT_SAGE = "/var/lib/jupyter/.sage";
    };

    serviceConfig = {
      Type = "simple";
      DynamicUser = true;
      StateDirectory = "jupyter";
      RuntimeDirectory = "jupyter";
      RuntimeDirectoryMode = "0750";
      CacheDirectory = "jupyter";

      # Load auth token from SOPS secret
      LoadCredential = [
        "auth-token:${config.sops.secrets."jupyterlab/auth-token".path}"
      ];

      # Security hardening (relaxed for SageMath compatibility)
      ProtectSystem = "strict";
      ProtectHome = true;
      PrivateTmp = true;
      NoNewPrivileges = true;
      # SageMath needs broader system access for mathematical computations
      # ProtectKernelTunables = true;  # Disabled for sage
      # ProtectKernelModules = true;   # Disabled for sage
      # ProtectControlGroups = true;   # Disabled for sage
      # RestrictAddressFamilies = [ "AF_INET" "AF_INET6" "AF_UNIX" ];  # Disabled for sage
      # RestrictNamespaces = true;     # Disabled for sage
      RestrictRealtime = true;
      RestrictSUIDSGID = true;
      # LockPersonality = true;        # Disabled for sage
      MemoryDenyWriteExecute = false;  # Disabled for Python JIT and sage
      # SystemCallFilter = "@system-service";  # Disabled - too restrictive for sage
      # SystemCallErrorNumber = "EPERM";

      # Resource limits
      MemoryMax = "8G";
      CPUQuota = "400%";  # Allow up to 4 cores

      # Restart policy
      Restart = "on-failure";
      RestartSec = "10s";
    };

    # Prepare JupyterLab environment and configuration
    preStart = ''
      # Read auth token from credential
      AUTH_TOKEN=$(cat "$CREDENTIALS_DIRECTORY/auth-token")

      # Create Jupyter config directory
      mkdir -p /var/lib/jupyter/config

      # Generate JupyterLab configuration
      cat > /var/lib/jupyter/config/jupyter_lab_config.py <<EOFPY
# JupyterLab Configuration
# Generated by NixOS

# Server settings
c.ServerApp.ip = '127.0.0.1'
c.ServerApp.port = 8888
c.ServerApp.open_browser = False
c.ServerApp.allow_root = False

# Authentication using token from SOPS
c.ServerApp.token = '$AUTH_TOKEN'
c.ServerApp.password = ""

# Disable password authentication (token only)
c.ServerApp.allow_password_change = False

# Trust all notebooks by default
c.ServerApp.trust_xheaders = True

# Working directory
c.ServerApp.root_dir = '/var/lib/jupyter/notebooks'

# Logging
c.Application.log_level = 'INFO'

# Allow remote access via proxy
c.ServerApp.allow_remote_access = True
c.ServerApp.base_url = '/'

# Kernel management
c.MultiKernelManager.default_kernel_name = 'python3'

# Enable collaborative editing (optional)
# c.LabApp.collaborative = True
EOFPY

      # Create notebooks directory
      mkdir -p /var/lib/jupyter/notebooks

      # Create a welcome notebook
      cat > /var/lib/jupyter/notebooks/Welcome.ipynb <<'NOTEBOOK'
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "welcome",
   "metadata": {},
   "source": [
    "# Welcome to JupyterLab with SageMath\\n",
    "\\n",
    "This JupyterLab instance is running on vulcan with SageMath kernel support.\\n",
    "\\n",
    "## Available Kernels\\n",
    "\\n",
    "- **Python 3**: Standard Python kernel\\n",
    "- **SageMath**: Mathematical computation system (use \\`Kernel > Change Kernel\\` to switch)\\n",
    "\\n",
    "## Quick Start\\n",
    "\\n",
    "### Python Example\\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "python-example",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Simple Python example\\n",
    "import sys\\n",
    "print(f\\"Python version: {sys.version}\\")\\n",
    "print(f\\"Hello from JupyterLab!\\")\\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sage-info",
   "metadata": {},
   "source": [
    "### SageMath Example\\n",
    "\\n",
    "To use SageMath, change the kernel to \\"SageMath\\" using the menu:\\n",
    "\\`Kernel > Change Kernel > SageMath\\`\\n",
    "\\n",
    "Then you can use SageMath commands like:\\n",
    "\\n",
    "\\`\\`\\`python\\n",
    "# Factor a number\\n",
    "factor(2^157 - 1)\\n",
    "\\n",
    "# Solve equations\\n",
    "x = var('x')\\n",
    "solve(x^2 - 4 == 0, x)\\n",
    "\\n",
    "# Plot functions\\n",
    "plot(sin(x), (x, -pi, pi))\\n",
    "\\`\\`\\`\\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
NOTEBOOK

      # SageMath comes with its own Jupyter kernel pre-installed
      # Just need to ensure directories exist
      mkdir -p /var/lib/jupyter/data/kernels
      mkdir -p /var/lib/jupyter/.sage

      # List available kernels (for logging/debugging)
      echo "Available Jupyter kernels:"
      ${sage}/bin/sage -sh -c "jupyter kernelspec list" || true

      # Set permissions
      chmod 600 /var/lib/jupyter/config/jupyter_lab_config.py
    '';

    # Start JupyterLab server using sage's built-in jupyterlab
    # This automatically includes the SageMath kernel
    script = ''
      exec ${sage}/bin/sage --notebook=jupyterlab \
        --no-browser \
        --ServerApp.config_file=/var/lib/jupyter/config/jupyter_lab_config.py \
        --ServerApp.root_dir=/var/lib/jupyter/notebooks \
        --ServerApp.ip=127.0.0.1 \
        --ServerApp.port=8888
    '';

    # Build Python environment with sage (includes everything)
    path = [
      sage
      pkgs.coreutils
      pkgs.bash
    ];
  };

  # JupyterLab nginx upstream with retry logic
  services.nginx.upstreams."jupyterlab" = {
    servers = {
      "127.0.0.1:8888" = {
        max_fails = 0;
      };
    };
    extraConfig = ''
      keepalive 16;
      keepalive_timeout 60s;
    '';
  };

  # Nginx virtual host for JupyterLab
  services.nginx.virtualHosts."jupyter.vulcan.lan" = {
    forceSSL = true;
    sslCertificate = "/var/lib/nginx-certs/jupyter.vulcan.lan.crt";
    sslCertificateKey = "/var/lib/nginx-certs/jupyter.vulcan.lan.key";

    locations."/" = {
      proxyPass = "http://jupyterlab/";
      proxyWebsockets = true;
      extraConfig = ''
        # Retry logic for temporary backend failures
        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_next_upstream_tries 3;
        proxy_next_upstream_timeout 10s;

        # Timeout settings for long-running computations
        proxy_connect_timeout 3600;
        proxy_send_timeout 3600;
        proxy_read_timeout 3600;

        # Buffer settings for notebook content
        proxy_buffering off;
        proxy_request_buffering off;
        client_max_body_size 500M;  # Allow large notebook uploads
      '';
    };
  };

  # Open firewall for local network access
  # HTTPS access via nginx on port 443 (already open globally in web.nix)
  networking.firewall.interfaces."end0".allowedTCPPorts = [
    8888 # JupyterLab web interface (for direct local access if needed)
  ];
}
