{ config, lib, pkgs, ... }:

let
  # SageMath for the kernel only
  sage = pkgs.sage;

  # JupyterLab environment from nixpkgs-unstable (defined in overlay)
  # This gives us:
  # - JupyterLab 4.5.0+ (from nixpkgs-unstable)
  # - PyTorch and TorchVision for ML workloads
  # - Common data science packages (numpy, pandas, matplotlib, scipy, etc.)
  # Uses unstable's Python to avoid version mismatch issues
  jupyterEnv = pkgs.jupyterlab-env;
in
{
  # SOPS secrets for JupyterLab
  sops.secrets."jupyterlab/auth-token" = {
    owner = "root";  # DynamicUser will access via systemd LoadCredential
    mode = "0400";
    restartUnits = [ "jupyterlab.service" ];
  };

  # JupyterLab service configuration
  systemd.services.jupyterlab = {
    description = "JupyterLab Server with SageMath Kernel and PyTorch";
    after = [ "network-online.target" "sops-install-secrets.service" ];
    wants = [ "network-online.target" "sops-install-secrets.service" ];
    wantedBy = [ "multi-user.target" ];

    # Environment for JupyterLab
    environment = {
      # Set HOME for sage (needs to create .sage directory)
      HOME = "/var/lib/jupyter";

      # Set Jupyter config directory
      JUPYTER_CONFIG_DIR = "/var/lib/jupyter/config";
      JUPYTER_DATA_DIR = "/var/lib/jupyter/data";
      JUPYTER_RUNTIME_DIR = "/run/jupyter";

      # Use system CA bundle (includes step-ca root CA)
      SSL_CERT_FILE = "/etc/ssl/certs/ca-bundle.crt";
      REQUESTS_CA_BUNDLE = "/etc/ssl/certs/ca-bundle.crt";

      # Sage-specific environment
      DOT_SAGE = "/var/lib/jupyter/.sage";
    };

    serviceConfig = {
      Type = "simple";
      DynamicUser = true;
      StateDirectory = "jupyter";
      RuntimeDirectory = "jupyter";
      RuntimeDirectoryMode = "0750";
      CacheDirectory = "jupyter";

      # Load auth token from SOPS secret
      LoadCredential = [
        "auth-token:${config.sops.secrets."jupyterlab/auth-token".path}"
      ];

      # Security hardening (relaxed for SageMath compatibility)
      ProtectSystem = "strict";
      ProtectHome = true;
      PrivateTmp = true;
      NoNewPrivileges = true;
      # SageMath needs broader system access for mathematical computations
      # ProtectKernelTunables = true;  # Disabled for sage
      # ProtectKernelModules = true;   # Disabled for sage
      # ProtectControlGroups = true;   # Disabled for sage
      # RestrictAddressFamilies = [ "AF_INET" "AF_INET6" "AF_UNIX" ];  # Disabled for sage
      # RestrictNamespaces = true;     # Disabled for sage
      RestrictRealtime = true;
      RestrictSUIDSGID = true;
      # LockPersonality = true;        # Disabled for sage
      MemoryDenyWriteExecute = false;  # Disabled for Python JIT and sage
      # SystemCallFilter = "@system-service";  # Disabled - too restrictive for sage
      # SystemCallErrorNumber = "EPERM";

      # Resource limits
      MemoryMax = "8G";
      CPUQuota = "400%";  # Allow up to 4 cores

      # Restart policy
      Restart = "on-failure";
      RestartSec = "10s";
    };

    # Prepare JupyterLab environment and configuration
    preStart = ''
      # Read auth token from credential
      AUTH_TOKEN=$(cat "$CREDENTIALS_DIRECTORY/auth-token")

      # Create Jupyter config directory
      mkdir -p /var/lib/jupyter/config

      # Generate JupyterLab configuration
      cat > /var/lib/jupyter/config/jupyter_lab_config.py <<EOFPY
# JupyterLab Configuration
# Generated by NixOS

# Server settings
c.ServerApp.ip = '127.0.0.1'
c.ServerApp.port = 8888
c.ServerApp.open_browser = False
c.ServerApp.allow_root = False

# Authentication using token from SOPS
c.ServerApp.token = '$AUTH_TOKEN'
c.ServerApp.password = ""

# Disable password authentication (token only)
c.ServerApp.allow_password_change = False

# Trust all notebooks by default
c.ServerApp.trust_xheaders = True

# Working directory
c.ServerApp.root_dir = '/var/lib/jupyter/notebooks'

# Logging
c.Application.log_level = 'INFO'

# Allow remote access via proxy
c.ServerApp.allow_remote_access = True
c.ServerApp.base_url = '/'

# Kernel management
c.MultiKernelManager.default_kernel_name = 'python3'

# Enable collaborative editing (optional)
# c.LabApp.collaborative = True
EOFPY

      # Create notebooks directory
      mkdir -p /var/lib/jupyter/notebooks

      # Create a welcome notebook with PyTorch examples
      cat > /var/lib/jupyter/notebooks/Welcome.ipynb <<'NOTEBOOK'
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "welcome",
   "metadata": {},
   "source": [
    "# Welcome to JupyterLab\n",
    "\n",
    "This JupyterLab instance is running on vulcan with SageMath kernel support and PyTorch.\n",
    "\n",
    "## Available Kernels\n",
    "\n",
    "- **Python 3**: Standard Python kernel with PyTorch, TorchVision, NumPy, Pandas, etc.\n",
    "- **SageMath**: Mathematical computation system (use `Kernel > Change Kernel` to switch)\n",
    "\n",
    "## Quick Start\n",
    "\n",
    "### Python + PyTorch Example\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "python-example",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Check Python and PyTorch versions\n",
    "import sys\n",
    "import torch\n",
    "import torchvision\n",
    "import numpy as np\n",
    "\n",
    "print(f\"Python version: {sys.version}\")\n",
    "print(f\"PyTorch version: {torch.__version__}\")\n",
    "print(f\"TorchVision version: {torchvision.__version__}\")\n",
    "print(f\"NumPy version: {np.__version__}\")\n",
    "print(f\"CUDA available: {torch.cuda.is_available()}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "torch-example",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Simple PyTorch tensor operations\n",
    "x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)\n",
    "y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)\n",
    "\n",
    "print(\"Matrix multiplication:\")\n",
    "print(torch.matmul(x, y))\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "sage-info",
   "metadata": {},
   "source": [
    "### SageMath Example\n",
    "\n",
    "To use SageMath, change the kernel to \"SageMath\" using the menu:\n",
    "`Kernel > Change Kernel > SageMath`\n",
    "\n",
    "Then you can use SageMath commands like:\n",
    "\n",
    "```python\n",
    "# Factor a number\n",
    "factor(2^157 - 1)\n",
    "\n",
    "# Solve equations\n",
    "x = var('x')\n",
    "solve(x^2 - 4 == 0, x)\n",
    "\n",
    "# Plot functions\n",
    "plot(sin(x), (x, -pi, pi))\n",
    "```\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
NOTEBOOK

      # Set up kernel directories
      mkdir -p /var/lib/jupyter/data/kernels
      mkdir -p /var/lib/jupyter/.sage

      # Install the SageMath kernel spec for our JupyterLab instance
      # Copy sage's kernel spec to our data directory
      SAGE_KERNEL_SRC="${sage}/share/jupyter/kernels/sagemath"
      if [ -d "$SAGE_KERNEL_SRC" ]; then
        cp -r "$SAGE_KERNEL_SRC" /var/lib/jupyter/data/kernels/sagemath
        echo "Installed SageMath kernel from: $SAGE_KERNEL_SRC"
      else
        # Fallback: create kernel spec manually
        mkdir -p /var/lib/jupyter/data/kernels/sagemath
        cat > /var/lib/jupyter/data/kernels/sagemath/kernel.json <<KERNELEOF
{
  "display_name": "SageMath",
  "language": "sage",
  "argv": [
    "${sage}/bin/sage",
    "--python",
    "-m",
    "sage.repl.ipython_kernel",
    "-f",
    "{connection_file}"
  ]
}
KERNELEOF
        echo "Created SageMath kernel spec manually"
      fi

      # List available kernels (for logging/debugging)
      echo "Available Jupyter kernels:"
      ${jupyterEnv}/bin/jupyter kernelspec list || true

      # Set permissions
      chmod 600 /var/lib/jupyter/config/jupyter_lab_config.py
    '';

    # Start JupyterLab server using our custom Python environment
    # with PyTorch, TorchVision, and other ML packages
    script = ''
      exec ${jupyterEnv}/bin/jupyter lab \
        --config=/var/lib/jupyter/config/jupyter_lab_config.py
    '';

    # Build environment with our custom Python env and sage for the kernel
    path = [
      jupyterEnv
      sage
      pkgs.coreutils
      pkgs.bash
    ];
  };

  # JupyterLab nginx upstream with retry logic
  services.nginx.upstreams."jupyterlab" = {
    servers = {
      "127.0.0.1:8888" = {
        max_fails = 0;
      };
    };
    extraConfig = ''
      keepalive 16;
      keepalive_timeout 60s;
    '';
  };

  # Nginx virtual host for JupyterLab
  services.nginx.virtualHosts."jupyter.vulcan.lan" = {
    forceSSL = true;
    sslCertificate = "/var/lib/nginx-certs/jupyter.vulcan.lan.crt";
    sslCertificateKey = "/var/lib/nginx-certs/jupyter.vulcan.lan.key";

    locations."/" = {
      proxyPass = "http://jupyterlab/";
      proxyWebsockets = true;
      extraConfig = ''
        # Retry logic for temporary backend failures
        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_next_upstream_tries 3;
        proxy_next_upstream_timeout 10s;

        # Timeout settings for long-running computations
        proxy_connect_timeout 3600;
        proxy_send_timeout 3600;
        proxy_read_timeout 3600;

        # Buffer settings for notebook content
        proxy_buffering off;
        proxy_request_buffering off;
        client_max_body_size 500M;  # Allow large notebook uploads
      '';
    };
  };

  # Open firewall for local network access
  # HTTPS access via nginx on port 443 (already open globally in web.nix)
  networking.firewall.interfaces."end0".allowedTCPPorts = [
    8888 # JupyterLab web interface (for direct local access if needed)
  ];
}
