{
  config,
  lib,
  pkgs,
  ...
}:

let
  # Get list of all backup names
  backupNames = builtins.attrNames config.services.restic.backups;

  # Create systemd overrides for each backup service
  mkBackupMonitoring = name: {
    "restic-backups-${name}" = {
      unitConfig = {
        # Add failure handling
        OnFailure = "backup-alert@%n.service";
      };
      serviceConfig = {
        # Add automatic restart with backoff
        Restart = lib.mkForce "on-failure";
        RestartSec = "30min";
        RestartSteps = 3;
        RestartMaxDelaySec = "2h";
      };
    };
  };

  # Merge all backup service overrides
  backupServiceOverrides = lib.mkMerge (map mkBackupMonitoring backupNames);

  # REMOVED 2026-07-28: the `backup_alerts` rule group (BackupServiceFailed,
  # BackupNotRunning, BackupTimerInactive) used to be generated here. All three were
  # PERMANENTLY INCAPABLE OF FIRING and had been since they were written:
  #
  #   count(systemd_unit_state)                             -> no data
  #   count(systemd_service_last_trigger_timestamp_seconds) -> no data
  #   count(node_systemd_unit_state)                        -> ~3065 series (fluctuates)
  #
  # The `systemd_*` metric family simply does not exist on this host; node-exporter
  # publishes `node_systemd_*`. BackupNotRunning additionally selected on a `unit` label,
  # which node-exporter does not use either (it is `name`).
  #
  # Why the 2026-06-09 fleet-wide dead-rule sweep missed these: that sweep audited
  # modules/monitoring/alerts/*.yaml, and these were generated by Nix inside a STORAGE
  # module via pkgs.writeText, so they never appeared in the file set being reviewed.
  # Rules defined outside alerts/*.yaml are invisible to that kind of audit -- worth
  # remembering before adding any new ones here.
  #
  # Deleted rather than repaired because live equivalents over metrics that DO exist
  # already run in modules/monitoring/alerts/health-checks.yaml (group
  # health_check_alerts), verified 9 series each:
  #   BackupServiceFailed   -> backup_service_failed == 1
  #   BackupNotRunRecently  -> (time() - backup_last_run_timestamp_seconds) > 129600
  #                            (identical 36h/129600s threshold, but note it measures the
  #                            SERVICE's last run rather than the TIMER's last trigger --
  #                            not literally like-for-like, and the stronger signal)
  #   BackupTimerInactive   -> backup_timer_active == 0   (dwell 5m -> 10m, the one
  #                            dwell that changed; +5min latency on a 36h-cadence signal)
  # A third BackupServiceFailed also exists in group systemd_service_health over
  # node_systemd_unit_state, so that condition is doubly covered.
in
{
  # Merge all systemd services into one definition
  systemd.services = lib.mkMerge [
    # Alert service template
    # Instantiated on demand only (no wantedBy — see the NOTE below); the
    # incorrect wantedBy=tank.mount was removed in commit 7e2f7fe.
    # ConditionPathIsMountPoint prevents "failed" status during rebuild when mount unavailable
    {
      "backup-alert@" = {
        description = "Backup failure alert for %i";
        after = [
          "zfs.target"
          "zfs-import-tank.service"
        ];
        # NOTE: Template units should not have wantedBy - they are instantiated on-demand
        # via OnFailure=backup-alert@%n.service from restic backup services
        unitConfig = {
          RequiresMountsFor = [ "/tank" ];
          ConditionPathIsMountPoint = "/tank";
        };
        serviceConfig = {
          Type = "oneshot";
          ExecStart = pkgs.writeShellScript "backup-alert" ''
            SERVICE_NAME="$1"
            TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

            # Log to systemd journal with high priority
            echo "BACKUP FAILURE: $SERVICE_NAME failed at $TIMESTAMP" | \
              ${pkgs.systemd}/bin/systemd-cat -p err -t backup-alert

            # Create a persistent alert file for monitoring
            ALERT_FILE="/var/lib/backup-alerts/$(echo "$SERVICE_NAME" | sed 's/[^a-zA-Z0-9-]/_/g').alert"
            mkdir -p /var/lib/backup-alerts
            echo "$TIMESTAMP" > "$ALERT_FILE"

            # If wallabag is running, create a notification there too
            if ${pkgs.systemd}/bin/systemctl is-active --quiet podman-wallabag; then
              echo "Backup failure: $SERVICE_NAME at $TIMESTAMP" >> /var/log/backup-failures.log
            fi
          '';
        };
      };

    }

    # Apply backup service overrides
    backupServiceOverrides
  ];

  # The backup_alerts rule file was REMOVED 2026-07-28 -- see the note where
  # backupRulesFile used to be defined, above. Coverage is unchanged: live equivalents
  # already exist in modules/monitoring/alerts/health-checks.yaml.

  # Create state directory for alerts
  systemd.tmpfiles.rules = [
    "d /var/lib/backup-alerts 0755 root root -"
    "f /var/log/backup-failures.log 0644 root root -"
  ];
}
