{
  config,
  lib,
  pkgs,
  ...
}:

{
  bindTankPath =
    {
      path,
      device,
      isReadOnly ? false,
    }:
    let
      # Convert device path to systemd mount unit name
      deviceUnitName = (lib.replaceStrings [ "/" ] [ "-" ] (lib.removePrefix "/" device)) + ".mount";
    in
    {
      "${path}" = {
        inherit device;
        options = [
          "bind"
          "nofail" # Don't block boot/activation if mount fails
          "x-systemd.requires-mounts-for=${device}" # Ensure source is mounted first
          "x-systemd.requires=${deviceUnitName}" # Explicit dependency on the ZFS mount unit
          "x-systemd.after=${deviceUnitName}" # Wait for ZFS dataset to mount
          "x-systemd.after=zfs.target"
          "x-systemd.after=zfs-import-tank.service"
          # ${deviceUnitName} is auto-generated by systemd only AFTER
          # zfs-mount.service has mounted the dataset, so ordering on it alone
          # races at boot: a slow pool import (e.g. the USB tank enclosure now on
          # the slower usb-storage driver) lets local-fs.target try the bind
          # before the source exists, and `nofail` then skips it *silently and
          # permanently* (ConditionResult=no, never retried), which in turn skips
          # every container/service that RequiresMountsFor it. Order+require the
          # concrete zfs-mount.service barrier (a real, always-present unit) so the
          # source dataset is guaranteed mounted first, regardless of import speed.
          # See memory project_tank_uas_enclosure_failure (2026-06-02 reboot).
          "x-systemd.requires=zfs-mount.service"
          "x-systemd.after=zfs-mount.service"
        ]
        ++ lib.optional isReadOnly "ro";
      };
    };
}
