# Synthetic Hermes traffic: generated by monitoring, never to be remembered.
#
# TWO consumers, and they MUST agree:
#
#   - modules/monitoring/services/hermes-health-check.nix SENDS `probePrompt` to
#     the agent on every scrape (via the hermes-mcp `ask_hermes` tool) and
#     asserts the reply contains `expectFragment`.
#   - modules/services/hermes-vm.nix renders `ignore` into the Qdrant memory
#     plugin's `write_filter`, which drops those exchanges at the write path
#     instead of storing them as turns.
#
# Keeping both sides in ONE file is the entire point. The probe fires every few
# minutes, so if the prompt text were changed in the health check alone the
# filter would go stale silently and the store would quietly resume filling with
# "ACK" — no error, no alert, just polluted recall. Change the text here and both
# sides move in the same rebuild.
#
# Why this is needed at all: the memory provider's write path (sync_turn) cannot
# tell a probe from a person. `_should_write()` already excludes cron/subagent/
# flush agent contexts, but the health probe arrives as an ordinary interactive
# session over the API server, so it passed straight through. Measured on
# 2026-08-04: 6 of 39 points in the collection were canary residue.
{
  # The end-to-end probe exchange. Deliberately tiny and deterministic.
  probePrompt = "Reply with the single word ACK and nothing else.";
  expectFragment = "ACK";

  ignore = {
    # Whitespace-normalised, case-insensitive equality. Cheapest check, and the
    # only place case-insensitivity is wanted: it catches a lowercase "ack" that
    # the deliberately case-sensitive ALL-CAPS pattern below will not.
    exact = [
      "ACK"
      "ACK."
    ];

    # Python `re` syntax, searched case-insensitively against each side of the
    # exchange (see pkgs/hermes-qdrant-memory/src/qdrant.py:_is_ignored).
    #
    # These match the SHAPE of a one-word canary, not specific words. The first
    # version of this file named ACK literally, and within the hour a second
    # canary appeared using ROVER and a trailing `/no_think`. Enumerating words
    # is a treadmill; a new canary of this shape now needs no change here.
    patterns = [
      # Any "Reply with the single word X and nothing else." probe, whatever X
      # is and whatever trails it (a `/no_think` directive, extra instructions).
      # Anchored at the start so a real message *quoting* the prompt — exactly
      # what a conversation about this filter looks like — is still remembered.
      "^\\s*Reply with the single word\\b"
      # The answer side: a bare ALL-CAPS single word, with optional trailing
      # punctuation the model may add. This side can be stored without its
      # prompt, so it needs its own rule.
      #
      # (?-i:...) is load-bearing. The whole filter compiles with IGNORECASE, so
      # an unscoped [A-Z] would swallow every one-word reply Hermes ever gives —
      # "why", "hello", "thanks" — and quietly delete real exchanges. The scoped
      # flag restores case-sensitivity for just this class. Verified available on
      # the guest's Python (3.12 and 3.13 both present; scoped flags need 3.11+).
      "^\\s*(?-i:[A-Z]{2,20})[.!]*\\s*$"
      # Manual opt-out for ad-hoc testing: put [nomem] anywhere in a message and
      # the exchange is not stored. Unanchored on purpose — the marker is
      # explicit intent wherever it appears.
      "\\[no-?mem(ory)?\\]"
    ];

    # Blanket short-message drop. OFF (0) deliberately: it condemns the whole
    # exchange, so a real one-word question ("why?") would discard the long,
    # useful answer with it. The patterns above are precise; this is not.
    minContentChars = 0;
  };
}
