# Synthetic Hermes traffic: generated by monitoring, never to be remembered.
#
# TWO consumers, and they MUST agree:
#
#   - modules/monitoring/services/hermes-health-check.nix SENDS `probePrompt` to
#     the agent on every scrape (via the hermes-mcp `ask_hermes` tool) and
#     asserts the reply contains `expectFragment`.
#   - modules/services/hermes-vm.nix renders `ignore` into the Qdrant memory
#     plugin's `write_filter`, which drops those exchanges at the write path
#     instead of storing them as turns.
#
# Keeping both sides in ONE file is the entire point. The probe fires every few
# minutes, so if the prompt text were changed in the health check alone the
# filter would go stale silently and the store would quietly resume filling with
# "ACK" — no error, no alert, just polluted recall. Change the text here and both
# sides move in the same rebuild.
#
# Why this is needed at all: the memory provider's write path (sync_turn) cannot
# tell a probe from a person. `_should_write()` already excludes cron/subagent/
# flush agent contexts, but the health probe arrives as an ordinary interactive
# session over the API server, so it passed straight through. Measured on
# 2026-08-04: 6 of 39 points in the collection were canary residue.
{
  # The end-to-end probe exchange. Deliberately tiny and deterministic.
  probePrompt = "Reply with the single word ACK and nothing else.";
  expectFragment = "ACK";

  ignore = {
    # Whitespace-normalised, case-insensitive equality. Cheapest check.
    exact = [
      "ACK"
      "ACK."
    ];

    # Python `re` syntax, searched case-insensitively against each side of the
    # exchange (see pkgs/hermes-qdrant-memory/src/qdrant.py:_is_ignored).
    patterns = [
      # The probe prompt. Anchored so a real message *quoting* it — which is
      # exactly what a conversation about this filter looks like — is still
      # remembered.
      "^\\s*Reply with the single word ACK\\b"
      # The one-word reply, tolerating trailing punctuation the model may add.
      "^\\s*ACK[\\s.!]*$"
      # Manual opt-out for ad-hoc testing: put [nomem] anywhere in a message and
      # the exchange is not stored. Unanchored on purpose — the marker is
      # explicit intent wherever it appears.
      "\\[no-?mem(ory)?\\]"
    ];

    # Blanket short-message drop. OFF (0) deliberately: it condemns the whole
    # exchange, so a real one-word question ("why?") would discard the long,
    # useful answer with it. The patterns above are precise; this is not.
    minContentChars = 0;
  };
}
