"""Loads the canonical zones.json generated by the NixOS module.

The Nix module owns the source of truth (zone list, thresholds, cycles).
This module just deserializes for Python consumers.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Zone:
    slug: str
    name: str
    type: str | None  # "spray" | "drip" | None

    @property
    def valve_entity_id(self) -> str:
        return f"valve.sprinkler_control_{self.slug}_zone"

    @property
    def gated_gpm_sensor(self) -> str:
        # HA slugifies the sensor "name" attribute, not the unique_id, so the
        # resulting entity_id is `water_<slug>_gated_gpm` (matches the name
        # "Water X Gated GPM"). Don't switch this to `_gpm_gated` — it'll
        # break every Phase 2/3 lookup. See docs/WATER_ATTRIBUTION.md.
        return f"sensor.water_{self.slug}_gated_gpm"

    @property
    def total_sensor(self) -> str:
        return f"sensor.water_{self.slug}_total"


@dataclass(frozen=True)
class AutofillConfig:
    gpm_min: float
    gpm_max: float
    window_minutes: int
    min_minutes_in_range: int
    enforce_mean_check: bool


@dataclass(frozen=True)
class Config:
    flume_current_sensor: str
    domestic_hot_flow_sensor: str | None
    autofill: AutofillConfig
    cycles: list[str]
    zones: list[Zone]
    victoriametrics_url: str
    ha_postgres_dsn: str


def load_config(path: str | Path) -> Config:
    """Read zones.json and return a typed Config.

    Raises KeyError on missing required fields.
    """
    raw = json.loads(Path(path).read_text())
    af = raw["autofill"]
    return Config(
        flume_current_sensor=raw["flume_current_sensor"],
        domestic_hot_flow_sensor=raw["domestic_hot_flow_sensor"],
        autofill=AutofillConfig(
            gpm_min=float(af["gpm_min"]),
            gpm_max=float(af["gpm_max"]),
            window_minutes=int(af["window_minutes"]),
            min_minutes_in_range=int(af["min_minutes_in_range"]),
            enforce_mean_check=bool(af["enforce_mean_check"]),
        ),
        cycles=list(raw["cycles"]),
        zones=[
            Zone(slug=z["slug"], name=z["name"], type=z.get("type"))
            for z in raw["zones"]
        ],
        victoriametrics_url=raw["victoriametrics_url"],
        ha_postgres_dsn=raw["ha_postgres_dsn"],
    )
