CREATE ROLE ${USER} WITH LOGIN PASSWORD ${PASS} CREATEDB;
CREATE DATABASE ${DB};
GRANT ALL PRIVILEGES ON DATABASE ${DB} TO ${USER};
\c ${DB}
GRANT ALL ON SCHEMA public TO ${USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${USER};
ALTER DATABASE ${DB} OWNER TO ${USER};
