# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, firmware, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usbhid" "usb_storage" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/06599d53-2177-4f41-a970-70ac651416ad";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FFF4-1EFC";
      fsType = "vfat";
      # Add systemd options to handle NVMe device detection race condition
      # on Apple Silicon hardware where boot device isn't always ready in time
      options = [
        "fmask=0022"
        "dmask=0022"
        "nofail"                        # Don't fail boot if mount fails
        "x-systemd.device-timeout=30s"  # Wait up to 30s for device
        "x-systemd.automount"           # Mount on first access
      ];
    };

  swapDevices = [ ];

  hardware.asahi.peripheralFirmwareDirectory = firmware;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.end0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
